### ISSUE TITLE
world.server Stagnation

### ISSUE THREAD

**Issue by mygithome002** [happy8541/stormDev#1]
http://i1.bvimg.com/577587/e6fd425ba70b16ba.jpg

**Comment by happy8541** [comment]
What kind of database do you use?
Here is my launch log. :)
https://pastebin.com/6r8djFQ7

**Comment by happy8541** [comment]
hey, any error with statrup? or?
With by BD start have 0 error. :)i commend in post.


2017-12-06 11:01 GMT+03:00 mygithome <notifications@github.com>:

**Comment by mygithome002** [comment]
I use arkcore-NG's database;Your original data is not open ah:)，GOOD LUCKY!
https://pastebin.com/RBViA0Fe

**Comment by happy8541** [comment]
hey. we make our database, becouse most ppls can open one-day servers.
And we cant share our database in public. But source can :)

2017-12-09 10:51 GMT+03:00 mygithome <notifications@github.com>:
