### ISSUE TITLE
Database?

### ISSUE THREAD

**Issue by cooler-SAI** [happy8541/stormDev#2]
hey! can you upload, please, full DB in zip? or rar. thanks anyway!
https://github.com/happy8541/stormDev/releases
хей! вы не могли бы выложить полностью рарник с полной базой? Спасибо в любом случае!

P>S> у вас есть пропущенные смарты! всё есть тут
https://github.com/cooler-SAI/patch

**Comment by happy8541** [comment]
Sorry, but not for public.

**Comment by happy8541** [comment]
If you put in public, you can build a bunch of one-day servers.
